#pragma once

#include "K_game.h"

enum {
    VAL_ARTILLERY_FIRE_SPEED,
    VAL_ARTILLERY_BULLET_SPEED,

    VAL_ARTILLERY_FIRE,
};

#define FLG_ARTILLERY_DEAD CUSTOM_FLAG(0)
#define FLG_ARTILLERY_BLOCKED CUSTOM_FLAG(1)
