#pragma once

#include "K_game.h"

enum {
	VAL_ARTILLERY_TIME = VAL_CUSTOM,
	VAL_ARTILLERY_ANGLE,
	VAL_ARTILLERY_ALPHA,
	VAL_ARTILLERY_HEIGHT,
};

enum {
	FLG_ARTILLERY_HOMING = CUSTOM_FLAG(0),
	FLG_ARTILLERY_DEAD = CUSTOM_FLAG(1),
	FLG_ARTILLERY_BLOCKED = CUSTOM_FLAG(2),
	FLG_ARTILLERY_SHIMMY = CUSTOM_FLAG(3),
};
