#pragma once

#include "K_game.h"

enum {
	VAL_WAVE_LENGTH = VAL_CUSTOM,
	VAL_WAVE_SPEED,
	VAL_WAVE_ANGLE,
	VAL_WAVE_DELTA,
};

enum {
	FLG_SCROLL_TANKS = CUSTOM_FLAG(0),
	FLG_SCROLL_BOWSER = CUSTOM_FLAG(1),

	FLG_WAVE_SKY = CUSTOM_FLAG(0),
	FLG_WAVE_START = CUSTOM_FLAG(1),
};
