#pragma once

#include "K_game.h"

typedef Uint8 BowserAnimations;
enum {
    BA_IDLE,
    BA_FIRE,
    BA_JUMP,
    BA_FIRE_END,
    BA_15,
    BA_16,
    BA_17,
    BA_18,
    BA_19,
};

enum {
    VAL_BOWSER_HEALTH,
    VAL_BOWSER_SPEED,
    VAL_BOWSER_JUMP_CHANCE,
    VAL_BOWSER_JUMP_SPEED,
    VAL_BOWSER_ATTACK_CHANCE,
    VAL_BOWSER_ATTACK_SPEED,
    VAL_BOWSER_PROJECTILE_SPEED,
    VAL_BOWSER_HURT_DURATION,

    VAL_BOWSER_ANIMATION,
    VAL_BOWSER_FRAME,

    VAL_BOWSER_MOVE,
    VAL_BOWSER_JUMP,
    VAL_BOWSER_ATTACK,
    VAL_BOWSER_HURT,
    VAL_BOWSER_FADE,
    VAL_BOWSER_HITS,
    VAL_BOWSER_K,
    VAL_BOWSER_L,
    VAL_BOWSER_M,
    VAL_BOWSER_N,
    VAL_BOWSER_O,

    VAL_BOWSER_Y,
    VAL_BOWSER_GUN,

    VAL_BOWSER_DEAD = 0,
    VAL_BOWSER_DEAD_LAVA,
    VAL_BOWSER_DEAD_Y,

    VAL_BOWSER_EFFECT_ANIMATION = 0,
    VAL_BOWSER_EFFECT_FRAME,
    VAL_BOWSER_EFFECT_ALPHA,
};

#define FLG_BOWSER_CHARGE CUSTOM_FLAG(0)
#define FLG_BOWSER_HAMMER CUSTOM_FLAG(1)
#define FLG_BOWSER_VOMIT CUSTOM_FLAG(2)
#define FLG_BOWSER_DEVASTATOR CUSTOM_FLAG(3)
#define FLG_BOWSER_GUN CUSTOM_FLAG(4)
#define FLG_BOWSER_HOMING CUSTOM_FLAG(5)
#define FLG_BOWSER_MOVING_BULLETS CUSTOM_FLAG(6)
#define FLG_BOWSER_HOMING_BULLETS CUSTOM_FLAG(7)
#define FLG_BOWSER_VOLCANO CUSTOM_FLAG(8)
#define FLG_BOWSER_GIGA CUSTOM_FLAG(9)

#define FLG_BOWSER_ACTIVE CUSTOM_FLAG(10)
#define FLG_BOWSER_RIGHT CUSTOM_FLAG(11)
#define FLG_BOWSER_FADE_IN CUSTOM_FLAG(12)
#define FLG_BOWSER_30 CUSTOM_FLAG(13)
