#pragma once

#include "K_game.h"

enum {
	VAL_BOWSER_HEALTH = VAL_CUSTOM,
	VAL_BOWSER_SPEED,
	VAL_BOWSER_JUMP_SPEED,
	VAL_BOWSER_FIRE_SPEED,
	VAL_BOWSER_MISSILE_SPEED,
	VAL_BOWSER_HURT_TIME,

	VAL_BOWSER_GUN,
	VAL_BOWSER_FRAME,
	VAL_BOWSER_GROUND,

	VAL_BOWSER_B,
	VAL_BOWSER_C,
	VAL_BOWSER_D,
	VAL_BOWSER_E,
	VAL_BOWSER_F,
	VAL_BOWSER_HURT,
	VAL_BOWSER_H,
	VAL_BOWSER_SLIPPER,
	VAL_BOWSER_SLIP,
	VAL_BOWSER_HITS,
	VAL_BOWSER_K,

	VAL_BOWSER_HEIGHT,

	VAL_KUPPA_BE_HAPPY = VAL_CUSTOM,

	VAL_KUPPA_LAVER = VAL_CUSTOM,
	VAL_KUPPA_PFRBRBR,
};

enum {
	FLG_BOWSER_CHARGE = CUSTOM_FLAG(0),
	FLG_BOWSER_HAMMER = CUSTOM_FLAG(1),
	FLG_BOWSER_VOMIT = CUSTOM_FLAG(2),
	FLG_BOWSER_GUN = CUSTOM_FLAG(3),
	FLG_BOWSER_DEVASTATOR = CUSTOM_FLAG(4),
	FLG_BOWSER_HOMING = CUSTOM_FLAG(5),
	FLG_BOWSER_MOVING_BULLETS = CUSTOM_FLAG(6),
	FLG_BOWSER_HOMING_BULLETS = CUSTOM_FLAG(7),
	FLG_BOWSER_GIGA = CUSTOM_FLAG(8),

	FLG_BOWSER_ACTIVE = CUSTOM_FLAG(9),
	FLG_BOWSER_1 = CUSTOM_FLAG(10),
	FLG_BOWSER_2 = CUSTOM_FLAG(11),
	FLG_BOWSER_10 = CUSTOM_FLAG(12),
	FLG_BOWSER_20 = CUSTOM_FLAG(13),
	FLG_BOWSER_21 = CUSTOM_FLAG(14),

	FLG_BOWSER_ANIM_FIRE_START = CUSTOM_FLAG(15),
	FLG_BOWSER_ANIM_JUMP = CUSTOM_FLAG(16),
	FLG_BOWSER_ANIM_FIRE = CUSTOM_FLAG(17),
	FLG_BOWSER_ANIM_FIRE_START2 = CUSTOM_FLAG(18),
	FLG_BOWSER_ANIM_SHELL = CUSTOM_FLAG(19),
	FLG_BOWSER_ANIMS = FLG_BOWSER_ANIM_FIRE_START | FLG_BOWSER_ANIM_JUMP | FLG_BOWSER_ANIM_FIRE
	                   | FLG_BOWSER_ANIM_FIRE_START2 | FLG_BOWSER_ANIM_SHELL,

	FLG_KUPPA_LAVA_LOVE = CUSTOM_FLAG(0),
};
