#pragma once

#include "K_game.h"

enum {
    VAL_CHECKPOINT_BOUNDS_X1 = VAL_CUSTOM,
    VAL_CHECKPOINT_BOUNDS_Y1,
    VAL_CHECKPOINT_BOUNDS_X2,
    VAL_CHECKPOINT_BOUNDS_Y2,
    VAL_CHECKPOINT_TRACK,
    VAL_CHECKPOINT_PLATFORM_X,
    VAL_CHECKPOINT_PLATFORM_Y,
    VAL_CHECKPOINT_ANIMATION,
    VAL_CHECKPOINT_FRAME,
    VAL_CHECKPOINT_STATE,

    VAL_CHECKPOINT_EFFECT_FRAME = VAL_CUSTOM,
    VAL_CHECKPOINT_EFFECT_ALPHA,
};

enum {
    FLG_CHECKPOINT_SET_PLATFORM = CUSTOM_FLAG(0),

    FLG_CHECKPOINT_EFFECT_TRAIL = CUSTOM_FLAG(0),
};
