#include "actors/K_enemies.h"

enum {
	VAL_KOOPA_MAYDAY = VAL_ENEMY_CUSTOM,

	VAL_SHELL_PLAYER = VAL_CUSTOM,
	VAL_SHELL_HIT,
	VAL_SHELL_COMBO,
	VAL_SHELL_FRAME,

	VAL_PARAKOOPA_Y = VAL_CUSTOM,
	VAL_PARAKOOPA_ANGLE,
};

enum {
	FLG_KOOPA_RED = CUSTOM_ENEMY_FLAG(0),

	FLG_SHELL_ACTIVE = CUSTOM_ENEMY_FLAG(1),

	FLG_PARAKOOPA_START = CUSTOM_ENEMY_FLAG(1),
};
