#pragma once

#include "actors/K_enemies.h"

enum {
    VAL_KOOPA_MAYDAY = VAL_ENEMY_CUSTOM,
    VAL_KOOPA_X,
    VAL_KOOPA_Y,
    VAL_KOOPA_ANGLE,

    VAL_SHELL_COOLDOWN = 0,
    VAL_SHELL_COMBO,
    VAL_SHELL_FRAME,
};

#define FLG_KOOPA_RED CUSTOM_ENEMY_FLAG(0)
#define FLG_KOOPA_HORIZONTAL CUSTOM_ENEMY_FLAG(1)
#define FLG_KOOPA_BOUNCE CUSTOM_ENEMY_FLAG(2)
