#pragma once

#include "K_game.h"

enum {
	VAL_LAKITU_FRAME = VAL_CUSTOM,
	VAL_LAKITU_THROW,
	VAL_LAKITU_STALL,
};

enum {
	FLG_LAKITU_GREEN = CUSTOM_FLAG(0),
	FLG_LAKITU_BLINK = CUSTOM_FLAG(1),
	FLG_LAKITU_CLOUD = CUSTOM_FLAG(2),
	FLG_LAKITU_IN = CUSTOM_FLAG(3),
	FLG_LAKITU_OUT = CUSTOM_FLAG(4),
	FLG_LAKITU_ANIMS = FLG_LAKITU_BLINK | FLG_LAKITU_CLOUD | FLG_LAKITU_IN | FLG_LAKITU_OUT,
};
