#pragma once

#include "K_game.h"

enum {
	VAL_MISSILE_PLAYER = VAL_CUSTOM,
	VAL_MISSILE_ANGLE,
	VAL_MISSILE_HITS,
	VAL_MISSILE_COOLDOWN,
	VAL_MISSILE_BUBBLE,
	VAL_MISSILE_HEIGHT,
};

enum {
	FLG_MISSILE_HIT = CUSTOM_FLAG(0),
	FLG_MISSILE_SINK = CUSTOM_FLAG(1),
	FLG_MISSILE_SHIMMY = CUSTOM_FLAG(2),
};
