#include "K_game.h"

enum {
	VAL_PLATFORM_TYPE = VAL_CUSTOM,
	VAL_PLATFORM_X,
	VAL_PLATFORM_Y,
	VAL_PLATFORM_X_SPEED,
	VAL_PLATFORM_Y_SPEED,
	VAL_PLATFORM_FLAGS,
	VAL_PLATFORM_RESPAWN,
	VAL_PLATFORM_FRAME,
	VAL_PLATFORM_X_FROM,
	VAL_PLATFORM_Y_FROM,
};

enum {
	FLG_PLATFORM_START = CUSTOM_FLAG(0),
	FLG_PLATFORM_ADD = CUSTOM_FLAG(1),
	FLG_PLATFORM_FALL = CUSTOM_FLAG(2),
	FLG_PLATFORM_WRAP = CUSTOM_FLAG(3),
	FLG_PLATFORM_FALLING = CUSTOM_FLAG(4),
};
