#include "K_game.h"

enum {
    VAL_PLAYER_GROUND = VAL_CUSTOM,
    VAL_PLAYER_ANIMATION,
    VAL_PLAYER_FRAME,

    VAL_PLAYER_EFFECT_CHARACTER = VAL_CUSTOM,
    VAL_PLAYER_EFFECT_POWERUP,
    VAL_PLAYER_EFFECT_FRAME,
    VAL_PLAYER_EFFECT_ALPHA,
};

enum {
    FLG_PLAYER_JUMP = CUSTOM_FLAG(0),
    FLG_PLAYER_DUCK = CUSTOM_FLAG(1),
    FLG_PLAYER_TOUCHED_WATER = CUSTOM_FLAG(2),
};
