#pragma once

#include "K_game.h"

typedef Uint8 PlatformType;
enum {
    PLAT_NORMAL,
    PLAT_SMALL,
    PLAT_CLOUD,
    PLAT_PURPLE,
    PLAT_BRICK,
    PLAT_GRASS,
    PLAT_GRASS_SMALL,
    PLAT_BRICK_BIG,
    PLAT_BRICK_TALL,
    PLAT_BRICK_SMALL,
    PLAT_BRICK_BUTTONS,
    PLAT_BLOCK,
};

/* ========
   PLATFORM
   ======== */

enum {
    VAL_PLATFORM_TYPE,
    VAL_PLATFORM_RUN_X_SPEED,
    VAL_PLATFORM_RUN_Y_SPEED,
    VAL_PLATFORM_RESPAWN,
    VAL_PLATFORM_START_X,
    VAL_PLATFORM_START_Y,
    VAL_PLATFORM_START_X_SPEED,
    VAL_PLATFORM_START_Y_SPEED,
    VAL_PLATFORM_START_FLAGS,

    FLG_PLATFORM_FALL = CUSTOM_FLAG(0),
    FLG_PLATFORM_WRAP = CUSTOM_FLAG(1),
    FLG_PLATFORM_RUN = CUSTOM_FLAG(2),
    FLG_PLATFORM_START = CUSTOM_FLAG(3),
    FLG_PLATFORM_FALLING = CUSTOM_FLAG(4),
    FLG_PLATFORM_RUNNING = CUSTOM_FLAG(5),
};

/* ===============
   PLATFORM TURNER
   =============== */

enum {
    VAL_PLATFORM_TURN_FLAGS_OFF,
    VAL_PLATFORM_TURN_FLAGS_ON,

    FLG_PLATFORM_TURN_ADD = CUSTOM_FLAG(0),
};
