#pragma once

#include "K_game.h"

enum {
    VAL_POWERUP_FRAME,
    VAL_POWERUP_OVERLAP,
};

#define FLG_POWERUP_CALAMITY CUSTOM_FLAG(0)
#define FLG_POWERUP_SPROUTED CUSTOM_FLAG(1)
#define FLG_POWERUP_BOUNCE CUSTOM_FLAG(2)
#define FLG_POWERUP_OVERLAP CUSTOM_FLAG(3)
