#pragma once

#include "K_game.h"

enum {
    VAL_PODOBOO_JUMP,
    VAL_PODOBOO_TIME,
    VAL_PODOBOO_Y,
    VAL_PODOBOO_OVERLAP,
    VAL_PODOBOO_FRAME,

    VAL_VOLCANO_TIME = 0,
    VAL_VOLCANO_FIRE_TIME,
    VAL_VOLCANO_FIRE_AMOUNT,

    VAL_VOLCANO_STATE,
    VAL_VOLCANO_FIRE_STATE,
    VAL_VOLCANO_FIRE,
};

#define FLG_PODOBOO_VOLCANO CUSTOM_FLAG(0)
