#pragma once

#include "K_game.h"

enum {
    VAL_PROJECTILE_HITS,
    VAL_PROJECTILE_ANGLE,

    FLG_PROJECTILE_HIT = CUSTOM_FLAG(0),
    FLG_PROJECTILE_HIT_ENEMY = CUSTOM_FLAG(1),
    FLG_PROJECTILE_HIT_BLOCK = CUSTOM_FLAG(2),
    FLG_PROJECTILE_OVERLAP = CUSTOM_FLAG(3),
    FLG_PROJECTILE_SINK = CUSTOM_FLAG(4),
};
