#include "K_game.h"

enum {
	VAL_ROTODISC_CHILD = VAL_CUSTOM,
	VAL_ROTODISC_PARENT = VAL_CUSTOM,
	VAL_ROTODISC_LENGTH,
	VAL_ROTODISC_ANGLE,
	VAL_ROTODISC_SPEED,
};

enum {
	FLG_ROTODISC_START = CUSTOM_FLAG(0),
	FLG_ROTODISC_FLOWER = CUSTOM_FLAG(1),
	FLG_ROTODISC_FLOWER2 = CUSTOM_FLAG(2),
};
