#pragma once

#include "actors/K_enemies.h"

enum {
	VAL_SPINY_FRAME = VAL_ENEMY_CUSTOM,
	VAL_SPINY_ANGLE,
};

enum {
	FLG_SPINY_GRAY = CUSTOM_ENEMY_FLAG(0),
	FLG_SPINY_GREEN = CUSTOM_ENEMY_FLAG(1),
	FLG_SPINY_HATCH = CUSTOM_ENEMY_FLAG(2),
	FLG_SPINY_ROLL = CUSTOM_ENEMY_FLAG(3),
};
