#pragma once

#include "K_game.h"

enum {
    VAL_WARP_X,
    VAL_WARP_Y,
    VAL_WARP_ANGLE,
    VAL_WARP_OUT_ANGLE,
    VAL_WARP_SECRET,
    VAL_WARP_TRACK,

    FLG_WARP_CALAMITY = CUSTOM_FLAG(0),
    FLG_WARP_SECRET = CUSTOM_FLAG(1),
    FLG_WARP_WORLD = CUSTOM_FLAG(2),
    FLG_WARP_LEVEL = CUSTOM_FLAG(3),
    FLG_WARP_DEVASTATOR = CUSTOM_FLAG(4),
    FLG_WARP_GOAL = CUSTOM_FLAG(5),
};
