#include "K_game.h"

enum {
	VAL_WARP_ANGLE = VAL_CUSTOM,
	VAL_WARP_X,
	VAL_WARP_Y,
	VAL_WARP_BOUNDS_X1,
	VAL_WARP_BOUNDS_Y1,
	VAL_WARP_BOUNDS_X2,
	VAL_WARP_BOUNDS_Y2,
	VAL_WARP_ANGLE_OUT,
	VAL_STRING(VAL_WARP_STRING),
};

enum {
	FLG_WARP_EXIT = CUSTOM_FLAG(0),
	FLG_WARP_SECRET = CUSTOM_FLAG(1),
	FLG_WARP_CALAMITY = CUSTOM_FLAG(2),
};
