#pragma once

#include "K_game.h"

enum {
    VAL_WARP_X,
    VAL_WARP_Y,
    VAL_WARP_ANGLE,
    VAL_WARP_OUT_ANGLE,
    VAL_WARP_BOUNDS_X1,
    VAL_WARP_BOUNDS_Y1,
    VAL_WARP_BOUNDS_X2,
    VAL_WARP_BOUNDS_Y2,
    VAL_WARP_TRACK,
    VAL_WARP_SECRET,
    VAL_WARP_ID,
    VAL_WARP_STATE,
};

#define FLG_WARP_CALAMITY CUSTOM_FLAG(0)
#define FLG_WARP_SECRET CUSTOM_FLAG(1)
#define FLG_WARP_WORLD CUSTOM_FLAG(2)
#define FLG_WARP_LEVEL CUSTOM_FLAG(3)
#define FLG_WARP_DEVASTATOR CUSTOM_FLAG(4)
#define FLG_WARP_GOAL CUSTOM_FLAG(5)
