#pragma once

#include "K_game.h"

enum {
	VAL_BLOCK_BUMP = VAL_CUSTOM,
	VAL_BLOCK_PLAYER,
	VAL_BLOCK_ITEM,
	VAL_BLOCK_TIME,
	VAL_BLOCK_BUMP_ANGLE,

	VAL_BRICK_SHARD_ANGLE = VAL_CUSTOM,
};

enum {
	FLG_BLOCK_EMPTY = CUSTOM_FLAG(0),
	FLG_BLOCK_GRAY = CUSTOM_FLAG(1),
	FLG_BLOCK_ONCE = CUSTOM_FLAG(2),
};
