#pragma once

#include "K_game.h"

enum {
	VAL_PLAYER_INDEX = VAL_CUSTOM,
	VAL_PLAYER_FRAME,
	VAL_PLAYER_GROUND,
	VAL_PLAYER_SPRING,
	VAL_PLAYER_POWER,
	VAL_PLAYER_FLASH,
	VAL_PLAYER_STARMAN,
	VAL_PLAYER_STARMAN_COMBO,
	VAL_PLAYER_FIRE,
	VAL_PLAYER_WARP,
	VAL_PLAYER_WARP_STATE,
	VAL_PLAYER_PLATFORM,
};

enum {
	FLG_PLAYER_DUCK = CUSTOM_FLAG(0),
	FLG_PLAYER_JUMP = CUSTOM_FLAG(1),
	FLG_PLAYER_SWIM = CUSTOM_FLAG(2),
	FLG_PLAYER_ASCEND = CUSTOM_FLAG(3),
	FLG_PLAYER_DESCEND = CUSTOM_FLAG(4),
	FLG_PLAYER_RESPAWN = CUSTOM_FLAG(5),
	FLG_PLAYER_STOMP = CUSTOM_FLAG(6),
	FLG_PLAYER_WARP_OUT = CUSTOM_FLAG(7),
	FLG_PLAYER_DEAD = CUSTOM_FLAG(8),
	FLG_PLAYER_CARRIED = CUSTOM_FLAG(9),
	FLG_PLAYER_JACKASS = CUSTOM_FLAG(10),
};

PlayerFrame get_player_frame(const GameActor*);
const char* get_player_texture(PlayerPower, PlayerFrame);

Bool hit_player(GameActor*);
void kill_player(GameActor*), win_player(GameActor*);
