#include "K_game.h"

#define ACTOR(ident)                                                                                                   \
	extern const GameActorTable TAB_##ident;                                                                       \
	ACTORS[ACT_##ident] = &TAB_##ident;

void populate_actors_table() {
	extern const GameActorTable* ACTORS[ACT_SIZE];

	ACTOR(PLAYER_SPAWN);
	ACTOR(PLAYER);
	ACTOR(PLAYER_DEAD);
	ACTOR(PLAYER_EFFECT);
	ACTOR(KEVIN);
	ACTOR(MISSILE_FIREBALL);
	ACTOR(MISSILE_BEETROOT);
	ACTOR(MISSILE_HAMMER);
	ACTOR(MISSILE_SILVER_HAMMER);
	ACTOR(CLOUD);
	ACTOR(BUSH);
	ACTOR(SOLID);
	ACTOR(SOLID_TOP);
	ACTOR(SOLID_SLOPE);
	ACTOR(WHEEL_LEFT);
	ACTOR(WHEEL);
	ACTOR(WHEEL_RIGHT);
	ACTOR(COIN);
	ACTOR(COIN_POP);
	ACTOR(POINTS);
	ACTOR(GOAL_BAR);
	ACTOR(GOAL_BAR_FLY);
	ACTOR(GOAL_MARK);
	ACTOR(ITEM_BLOCK);
	ACTOR(HIDDEN_BLOCK);
	ACTOR(BRICK_BLOCK);
	ACTOR(BRICK_SHARD);
	ACTOR(COIN_BLOCK);
	ACTOR(NOTE_BLOCK);
	ACTOR(BLOCK_BUMP);
	ACTOR(PSWITCH);
	ACTOR(PSWITCH_COIN);
	ACTOR(PSWITCH_BRICK);
	ACTOR(MUSHROOM);
	ACTOR(MUSHROOM_1UP);
	ACTOR(MUSHROOM_POISON);
	ACTOR(FIRE_FLOWER);
	ACTOR(BEETROOT);
	ACTOR(LUI);
	ACTOR(HAMMER_SUIT);
	ACTOR(STARMAN);
	ACTOR(AUTOSCROLL);
	ACTOR(BOUNDS);
	ACTOR(CHECKPOINT);
	ACTOR(PLATFORM);
	ACTOR(PLATFORM_TURN);
	ACTOR(EXPLODE);
	ACTOR(BULLET_BILL);
	ACTOR(BILL_BLASTER);
	ACTOR(DEAD);
	ACTOR(PIRANHA_PLANT);
	ACTOR(PIRANHA_FIRE);
	ACTOR(THWOMP);
	ACTOR(SPIKE_CANNON);
	ACTOR(SPIKE_BALL);
	ACTOR(SPIKE_BALL_EFFECT);
	ACTOR(ROTODISC_BALL);
	ACTOR(ROTODISC);
	ACTOR(WATER_SPLASH);
	ACTOR(BUBBLE);
	ACTOR(KOOPA);
	ACTOR(KOOPA_SHELL);
	ACTOR(PARAKOOPA);
	ACTOR(SPINY);
	ACTOR(BRO);
	ACTOR(BRO_LAYER);
	ACTOR(GOOMBA);
	ACTOR(GOOMBA_FLAT);
	ACTOR(WARP);
	ACTOR(LAVA);
	ACTOR(PODOBOO);
	ACTOR(PODOBOO_VOLCANO);
	ACTOR(LAVA_SPLASH);
	ACTOR(CHEEP_CHEEP_BLUE);
	ACTOR(CHEEP_CHEEP_SPIKY);
	ACTOR(BOWSER);
	ACTOR(SPRING);

	static const GameActorTable TAB_NULL = {0};
	ACTORS[ACT_NULL] = &TAB_NULL;
}
