#pragma once

// #include order matters!
// clang-format off
#include <glad/gl.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_opengl.h>
// clang-format on

#define WHITE (GLubyte[4]){255, 255, 255, 255}
#define GRAY (GLubyte[4]){128, 128, 128, 255}
#define BLACK (GLubyte[4]){0, 0, 0, 255}

#define RGB(r, g, b) (GLubyte[4]){r, g, b, 255}

#define RGBA(r, g, b, a)                                                                                               \
    (GLubyte[4]) {                                                                                                     \
        r, g, b, a                                                                                                     \
    }

#define ALPHA(a)                                                                                                       \
    (GLubyte[4]) {                                                                                                     \
        255, 255, 255, a                                                                                               \
    }

enum VertexAttributes {
    VATT_POSITION,
    VATT_COLOR,
    VATT_UV,
};

enum TextureIndices {
    TEX_NULL,

    TEX_GRASS1,
    TEX_GRASS2,
    TEX_GRASS3,
    TEX_GRASS4,
    TEX_GRASS5,
    TEX_GRASS6,
    TEX_GRASS7,
    TEX_GRASS8,
    TEX_GRASS9,
    TEX_ISLAND1,
    TEX_ISLAND2,
    TEX_ISLAND3,
    TEX_ISLAND4,
    TEX_ISLAND5,
    TEX_ISLAND6,
    TEX_ISLAND7,
    TEX_ISLAND8,
    TEX_ISLAND9,
    TEX_UNDERWATER1,
    TEX_UNDERWATER2,
    TEX_UNDERWATER3,
    TEX_UNDERWATER4,
    TEX_UNDERWATER5,
    TEX_UNDERWATER6,
    TEX_UNDERWATER7,
    TEX_UNDERWATER8,
    TEX_UNDERWATER9,
    TEX_UNDERWATER_BLOCK,
    TEX_UNDERWATER_CORAL,
    TEX_STARLAND1,
    TEX_STARLAND2,
    TEX_STARLAND3,
    TEX_STARLAND4,
    TEX_STARLAND5,
    TEX_STARLAND6,
    TEX_STARLAND7,
    TEX_STARLAND8,
    TEX_STARLAND9,
    TEX_STARLAND_STAR1,
    TEX_STARLAND_STAR2,
    TEX_STARLAND_STAR3,
    TEX_STARLAND_STAR4,
    TEX_SNOW1,
    TEX_SNOW2,
    TEX_SNOW3,
    TEX_SNOW4,
    TEX_SNOW5,
    TEX_SNOW6,
    TEX_SNOW7,
    TEX_SNOW8,
    TEX_SNOW9,
    TEX_DESERT1,
    TEX_DESERT2,
    TEX_DESERT3,
    TEX_DESERT4,
    TEX_DESERT5,
    TEX_DESERT6,
    TEX_DESERT7,
    TEX_DESERT8,
    TEX_DESERT9,
    TEX_CAVE1,
    TEX_CAVE2,
    TEX_CAVE3,
    TEX_CAVE4,
    TEX_CAVE5,
    TEX_CAVE6,
    TEX_CAVE7,
    TEX_CAVE8,
    TEX_CAVE9,
    TEX_CASTLE1,
    TEX_CASTLE2,
    TEX_CASTLE3,
    TEX_CASTLE4,
    TEX_CASTLE5,
    TEX_CASTLE6,
    TEX_CASTLE7,
    TEX_CASTLE8,
    TEX_CASTLE9,
    TEX_CASTLE_STAIRS1,
    TEX_CASTLE_STAIRS2,
    TEX_CASTLE_STAIRS3,
    TEX_CASTLE_STAIRS4,
    TEX_CASTLE_STAIRS5,
    TEX_CASTLE_STAIRS6,
    TEX_CASTLE_STAIRS7,
    TEX_CASTLE_STAIRS8,
    TEX_CASTLE_STAIRS9,
    TEX_CASTLE_BRIDGE1,
    TEX_CASTLE_BRIDGE2,
    TEX_CASTLE_BRIDGE3,
    TEX_CASTLE_BRIDGE4,
    TEX_BLOCK1,
    TEX_BLOCK2,
    TEX_BLOCK3,
    TEX_BLOCK4,
    TEX_BRICK1,
    TEX_BRICK2,
    TEX_BRICK3,
    TEX_BRICK4,
    TEX_BRICK5,
    TEX_BRIDGE1,
    TEX_BRIDGE2,
    TEX_BRIDGE3,
    TEX_PIPE1_H1,
    TEX_PIPE1_H2,
    TEX_PIPE1_H3,
    TEX_PIPE1_V1,
    TEX_PIPE1_V2,
    TEX_PIPE1_V3,
    TEX_PIPE2_H1,
    TEX_PIPE2_H2,
    TEX_PIPE2_H3,
    TEX_PIPE2_V1,
    TEX_PIPE2_V2,
    TEX_PIPE2_V3,
    TEX_PIPE3_H1,
    TEX_PIPE3_H2,
    TEX_PIPE3_H3,
    TEX_PIPE3_V1,
    TEX_PIPE3_V2,
    TEX_PIPE3_V3,
    TEX_PIPE4_H1,
    TEX_PIPE4_H2,
    TEX_PIPE4_H3,
    TEX_PIPE4_V1,
    TEX_PIPE4_V2,
    TEX_PIPE4_V3,
    TEX_TANK1,
    TEX_TANK2,
    TEX_TANK3,
    TEX_TANK_BLOCK,
    TEX_TANK_SLOPE1,
    TEX_TANK_SLOPE2,
    TEX_TANK_SMASH,
    TEX_TANK_NAILS1,
    TEX_TANK_NAILS2,
    TEX_TANK_PILLAR1,
    TEX_TANK_PILLAR2,
    TEX_TANK_PILLAR3,
    TEX_TANK_CHAIN,
    TEX_TANK_WHEEL1_1,
    TEX_TANK_WHEEL1_2,
    TEX_TANK_WHEEL1_3,
    TEX_TANK_WHEEL2_1,
    TEX_TANK_WHEEL2_2,
    TEX_TANK_WHEEL2_3,
    TEX_TANK_WHEEL2_4,
    TEX_TANK_WHEEL3_1,
    TEX_TANK_WHEEL3_2,
    TEX_TANK_WHEEL3_3,
    TEX_TANK_BOWSER1,
    TEX_TANK_BOWSER2,
    TEX_CLOUD1,
    TEX_CLOUD2,
    TEX_CLOUD3,
    TEX_CLOUD_DARK1,
    TEX_CLOUD_DARK2,
    TEX_CLOUD_DARK3,
    TEX_BUSH1,
    TEX_BUSH2,
    TEX_BUSH3,
    TEX_BUSH_SNOW1,
    TEX_BUSH_SNOW2,
    TEX_BUSH_SNOW3,
    TEX_TREE1,
    TEX_TREE2,
    TEX_TREE2_BACK,
    TEX_TREE3,
    TEX_TREE_HAPPY1,
    TEX_TREE_HAPPY2,
    TEX_TREE_HAPPY3,
    TEX_TREE_HAPPY4,
    TEX_TREE_HAPPY5,
    TEX_TREE_STARLAND1,
    TEX_TREE_STARLAND2,
    TEX_TREE_SNOW1,
    TEX_TREE_SNOW2,
    TEX_TREE_DESERT1,
    TEX_TREE_DESERT2,
    TEX_CACTUS1,
    TEX_CACTUS2,
    TEX_CACTUS3,
    TEX_FENCE1,
    TEX_FENCE2,
    TEX_FENCE3,
    TEX_FENCE_SNOW1,
    TEX_FENCE_SNOW2,
    TEX_FENCE_SNOW3,
    TEX_WATERFALL1,
    TEX_WATERFALL2,
    TEX_WATERFALL3,
    TEX_WATERFALL4,
    TEX_PILLAR1,
    TEX_PILLAR2,
    TEX_PILLAR3,
    TEX_SUPPORT1,
    TEX_SUPPORT2,
    TEX_HILL1,
    TEX_HILL2,
    TEX_HILL3,
    TEX_HILL_STARLAND,
    TEX_HILL_SNOW,
    TEX_HILLS,
    TEX_HILLS_SNOW,
    TEX_FOREST,
    TEX_ROCKS,
    TEX_PYRAMID,
    TEX_CLOUDS,
    TEX_CLOUDS_FACE1,
    TEX_CLOUDS_FACE2,
    TEX_CLOUDS_FACE3,
    TEX_CLOUDS_FACE4,
    TEX_CLOUDS_FACE5,
    TEX_CLOUDS_FACE6,
    TEX_CLOUDS_FACE7,
    TEX_CLOUDS_FACE8,
    TEX_CLOUDS_FACE9,
    TEX_CLOUDS_FACE10,
    TEX_BOWSER_PIC1,
    TEX_BOWSER_PIC2,
    TEX_BOWSER_PIC3,
    TEX_BOWSER_EYES1,
    TEX_BOWSER_EYES2,
    TEX_BOWSER_EYES3,
    TEX_BOWSER_EYES4,
    TEX_BOWSER_EYES5,
    TEX_BOWSER_EYES6,
    TEX_BOWSER_EYES7,
    TEX_SIGN_HARDCORE,
    TEX_SIGN_HUMAN_LAB,
    TEX_SIGN_HUMAN_HOUSE,
    TEX_SIGN_HUMAN_END,
    TEX_SIGN_UP,
    TEX_SIGN_LEFT,
    TEX_SIGN_DOWN,
    TEX_SIGN_RIGHT,
    TEX_SIGN_HARDCORE_1_4,
    TEX_SIGN_LAKITUS,
    TEX_BG_CLOUDS1,
    TEX_BG_CLOUDS2,
    TEX_BG_STARLAND,
    TEX_BG_DESERT,
    TEX_BG_UNDERWATER,
    TEX_BG_CAVE1,
    TEX_BG_CAVE2,
    TEX_BG_CASTLE1,
    TEX_BG_CASTLE2,
    TEX_BG_CASTLE3,
    TEX_BG_CASTLE4,
    TEX_BG_CASTLE5,
    TEX_BG_CASTLE6,
    TEX_MARIO_DEAD,
    TEX_MARIO_SMALL,
    TEX_MARIO_SMALL_WALK1,
    TEX_MARIO_SMALL_WALK2,
    TEX_MARIO_SMALL_JUMP,
    TEX_MARIO_SMALL_SWIM1,
    TEX_MARIO_SMALL_SWIM2,
    TEX_MARIO_SMALL_SWIM3,
    TEX_MARIO_SMALL_SWIM4,
    TEX_MARIO_BIG_GROW,
    TEX_MARIO_BIG,
    TEX_MARIO_BIG_WALK1,
    TEX_MARIO_BIG_WALK2,
    TEX_MARIO_BIG_JUMP,
    TEX_MARIO_BIG_DUCK,
    TEX_MARIO_BIG_SWIM1,
    TEX_MARIO_BIG_SWIM2,
    TEX_MARIO_BIG_SWIM3,
    TEX_MARIO_BIG_SWIM4,
    TEX_MARIO_FIRE_GROW1,
    TEX_MARIO_FIRE_GROW2,
    TEX_MARIO_FIRE,
    TEX_MARIO_FIRE_WALK1,
    TEX_MARIO_FIRE_WALK2,
    TEX_MARIO_FIRE_JUMP,
    TEX_MARIO_FIRE_DUCK,
    TEX_MARIO_FIRE_FIRE,
    TEX_MARIO_FIRE_SWIM1,
    TEX_MARIO_FIRE_SWIM2,
    TEX_MARIO_FIRE_SWIM3,
    TEX_MARIO_FIRE_SWIM4,
    TEX_MARIO_BEETROOT,
    TEX_MARIO_BEETROOT_WALK1,
    TEX_MARIO_BEETROOT_WALK2,
    TEX_MARIO_BEETROOT_JUMP,
    TEX_MARIO_BEETROOT_DUCK,
    TEX_MARIO_BEETROOT_FIRE,
    TEX_MARIO_BEETROOT_SWIM1,
    TEX_MARIO_BEETROOT_SWIM2,
    TEX_MARIO_BEETROOT_SWIM3,
    TEX_MARIO_BEETROOT_SWIM4,
    TEX_MARIO_LUI,
    TEX_MARIO_LUI_WALK1,
    TEX_MARIO_LUI_WALK2,
    TEX_MARIO_LUI_JUMP,
    TEX_MARIO_LUI_DUCK,
    TEX_MARIO_LUI_SWIM1,
    TEX_MARIO_LUI_SWIM2,
    TEX_MARIO_LUI_SWIM3,
    TEX_MARIO_LUI_SWIM4,
    TEX_MARIO_HAMMER,
    TEX_MARIO_HAMMER_WALK1,
    TEX_MARIO_HAMMER_WALK2,
    TEX_MARIO_HAMMER_JUMP,
    TEX_MARIO_HAMMER_DUCK,
    TEX_MARIO_HAMMER_FIRE,
    TEX_MARIO_HAMMER_SWIM1,
    TEX_MARIO_HAMMER_SWIM2,
    TEX_MARIO_HAMMER_SWIM3,
    TEX_MARIO_HAMMER_SWIM4,
    TEX_COIN1,
    TEX_COIN2,
    TEX_COIN3,
    TEX_COIN_POP1,
    TEX_COIN_POP2,
    TEX_COIN_POP3,
    TEX_COIN_POP4,
    TEX_COIN_SPARK1,
    TEX_COIN_SPARK2,
    TEX_COIN_SPARK3,
    TEX_COIN_SPARK4,
    TEX_MUSHROOM,
    TEX_MUSHROOM_1UP,
    TEX_MUSHROOM_POISON1,
    TEX_MUSHROOM_POISON2,
    TEX_FIRE_FLOWER1,
    TEX_FIRE_FLOWER2,
    TEX_FIRE_FLOWER3,
    TEX_FIRE_FLOWER4,
    TEX_BEETROOT1,
    TEX_BEETROOT2,
    TEX_BEETROOT3,
    TEX_LUI1,
    TEX_LUI2,
    TEX_LUI3,
    TEX_LUI4,
    TEX_LUI5,
    TEX_LUI_BOUNCE1,
    TEX_LUI_BOUNCE2,
    TEX_LUI_BOUNCE3,
    TEX_HAMMER_SUIT,
    TEX_STARMAN1,
    TEX_STARMAN2,
    TEX_STARMAN3,
    TEX_STARMAN4,
    TEX_EXPLODE1,
    TEX_EXPLODE2,
    TEX_EXPLODE3,
    TEX_MISSILE_FIREBALL,
    TEX_MISSILE_BEETROOT,
    TEX_MISSILE_HAMMER,
    TEX_MISSILE_SILVER_HAMMER,
    TEX_MISSILE_SPIKE_BALL,
    TEX_100,
    TEX_200,
    TEX_500,
    TEX_1000,
    TEX_2000,
    TEX_5000,
    TEX_10000,
    TEX_1000000,
    TEX_1UP,
    TEX_ITEM_BLOCK1,
    TEX_ITEM_BLOCK2,
    TEX_ITEM_BLOCK3,
    TEX_EMPTY_BLOCK,
    TEX_BRICK_BLOCK,
    TEX_BRICK_BLOCK_GRAY,
    TEX_BRICK_SHARD,
    TEX_BRICK_SHARD_GRAY,
    TEX_CHECKPOINT1,
    TEX_CHECKPOINT2,
    TEX_CHECKPOINT3,
    TEX_ROTODISC_BALL,
    TEX_ROTODISC1,
    TEX_ROTODISC2,
    TEX_ROTODISC3,
    TEX_ROTODISC4,
    TEX_ROTODISC5,
    TEX_ROTODISC6,
    TEX_ROTODISC7,
    TEX_ROTODISC8,
    TEX_ROTODISC9,
    TEX_ROTODISC10,
    TEX_ROTODISC11,
    TEX_ROTODISC12,
    TEX_ROTODISC13,
    TEX_ROTODISC14,
    TEX_ROTODISC15,
    TEX_ROTODISC16,
    TEX_ROTODISC17,
    TEX_ROTODISC18,
    TEX_ROTODISC19,
    TEX_ROTODISC20,
    TEX_ROTODISC21,
    TEX_ROTODISC22,
    TEX_ROTODISC23,
    TEX_ROTODISC24,
    TEX_ROTODISC25,
    TEX_ROTODISC26,
    TEX_FONT_MAIN,
    TEX_FONT_HUD,
    TEX_HUD_COINS1,
    TEX_HUD_COINS2,
    TEX_HUD_COINS3,
    TEX_GOAL_MARK,
    TEX_GOAL,
    TEX_GOAL_BAR1,
    TEX_GOAL_BAR2,
    TEX_WATER1,
    TEX_WATER2,
    TEX_WATER3,
    TEX_WATER4,
    TEX_WATER5,
    TEX_WATER6,
    TEX_WATER7,
    TEX_WATER8,
    TEX_WATER_SPLASH1,
    TEX_WATER_SPLASH2,
    TEX_WATER_SPLASH3,
    TEX_WATER_SPLASH4,
    TEX_WATER_SPLASH5,
    TEX_WATER_SPLASH6,
    TEX_WATER_SPLASH7,
    TEX_WATER_SPLASH8,
    TEX_WATER_SPLASH9,
    TEX_WATER_SPLASH10,
    TEX_WATER_SPLASH11,
    TEX_WATER_SPLASH12,
    TEX_WATER_SPLASH13,
    TEX_WATER_SPLASH14,
    TEX_WATER_SPLASH15,
    TEX_BUBBLE,
    TEX_BUBBLE_POP1,
    TEX_BUBBLE_POP2,
    TEX_BUBBLE_POP3,
    TEX_BUBBLE_POP4,
    TEX_BUBBLE_POP5,
    TEX_BUBBLE_POP6,
    TEX_BUBBLE_POP7,

    TEX_SIZE,
};

enum FontIndices {
    FNT_NULL,
    FNT_MAIN,
    FNT_HUD,
    FNT_SIZE,
};

enum FontAlignment {
    FA_LEFT = 0,
    FA_TOP = 0,
    FA_CENTER = 1,
    FA_RIGHT = 2,
    FA_BOTTOM = 2,
};

struct Uniforms {
    GLint mvp;
    GLint texture;
    GLint alpha_test;
};

struct Texture {
    const char* name;
    GLuint texture;
    GLuint size[2];
    GLfloat offset[2];
};

struct Font {
    enum TextureIndices texture;

    GLfloat spacing;
    GLfloat line_height;
    struct Glyph {
        GLfloat size[2], uvs[4];
    } glyphs[256];
};

struct Vertex {
    GLfloat position[3];
    GLubyte color[4];
    GLfloat uv[2];
};

struct VertexBatch {
    GLuint vao, vbo;
    size_t vertex_count, vertex_capacity;
    struct Vertex* vertices;

    GLfloat color[4];
    GLuint texture;
    GLfloat alpha_test;
    GLenum blend_src[2], blend_dest[2];
    bool filter;
};

struct TileBatch {
    struct TileBatch* next;

    GLuint texture;
    GLuint vao, vbo;
    size_t vertex_count, vertex_capacity;
    struct Vertex* vertices;
};

void video_init(bool);
void video_update();
void video_teardown();

void move_camera(float, float);

void load_texture(enum TextureIndices);
void load_font(enum FontIndices);

void submit_batch();
void batch_vertex(GLfloat, GLfloat, GLfloat, GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat);
void clear_tiles();
void add_gradient(GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLubyte[4][4]);
void add_backdrop(enum TextureIndices, GLfloat, GLfloat, GLfloat, GLubyte, GLubyte, GLubyte, GLubyte);
void draw_sprite(enum TextureIndices, const float[3], const bool[2], GLfloat, const GLubyte[4]);
void draw_text(enum FontIndices, enum FontAlignment, const char*, const float[3]);
void draw_rectangle(enum TextureIndices, const float[2][2], float, const GLubyte[4]);
