name: Build & release

on:
  push:
    branches: ["master"]
    tags: ["stable", "dev"]

jobs:
  binary:
    name: Release binaries for ${{ matrix.config.os-name }}
    runs-on: ${{ matrix.config.runner-os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - os-name: Win64
            runner-os: windows-latest
            bin-ext: .exe
    env:
      OUTFILE: Klawiatura-${{ matrix.config.os-name }}-${{ github.ref_name }}.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Source fmod legally
        uses: actions/checkout@v4
        with:
          repository: toggins/fmod
          token: ${{ secrets.FMOD_TOKEN }}
          path: include/fmod
          ref: master
      - name: Install Python deps
        run: py -m pip install jinja2
      - name: Restore build cache
        uses: actions/cache/restore@v4
        id: cache-load
        with:
          path: build
          key: cmake-${{ github.ref_name }}-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
      - name: Build
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --target Klawiatura
      - name: Save build cache
        uses: actions/cache/save@v4
        id: cache-save
        with:
          path: build
          key: cmake-${{ github.ref_name }}-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
      - name: Assemble
        run: |
          New-Item -Force -Path 'Klawiatura' -ItemType 'Directory'
          Copy-Item -Recurse -Destination 'Klawiatura' -Path @('build/Klawiatura.exe', 'build/fmodL.dll', 'build/data')
          7z a $env:OUTFILE Klawiatura\
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ env.OUTFILE }}
      - name: Release (dev)
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'branch'
        with:
          tag_name: dev
          files: ${{ env.OUTFILE }}
