name: Build and release distributions

on:
  push:
    branches: [master]
    tags: [v*]
    paths-ignore:
      - README.md
      - .*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CRAZY_AHH_DEPS: >-
    python3-jinja2
    libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev
    libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev
    libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev
    libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev
    libibus-1.0-dev libudev-dev libthai-dev libpipewire-0.3-dev libwayland-dev
    libdecor-0-dev liburing-dev

jobs:
  release-linux:
    name: Publish Linux binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      CACHE_BUST: 1
      OUTNAME: Klawiatura-${{ github.ref_name == 'master' && 'dev' || github.ref_name }}-Linux

    steps:
      - name: Silence `git init` warning
        run: git config --global init.defaultBranch master

      - name: Checkout
        uses: actions/checkout@v7

      - name: Source Discord Social SDK
        run: |
          cd external/discord; git init
          git remote add origin https://${{ secrets.EXTERNAL_TOKEN }}@github.com/${{ secrets.EXTERNAL_USER }}/discord.git
          git pull origin master

      - name: Restore source timestamps for crazy CMake caching benefits
        uses: chetan/git-restore-mtime-action@v2

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          version: 1.4
          packages: ${{ env.CRAZY_AHH_DEPS }}

      - name: Cache build dir
        id: cache-build
        uses: actions/cache@v6
        with:
          path: build
          key: ${{ env.CACHE_BUST }}-Linux-${{ github.ref_name }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ env.CACHE_BUST }}-Linux-${{ github.ref_name }}-
            ${{ env.CACHE_BUST }}-Linux-

      - name: Configure
        run: >-
          cmake -G Ninja -S . -B build
            -D CMAKE_BUILD_TYPE=Release
            -D CPACK_PACKAGE_FILE_NAME=${{ env.OUTNAME }}

      - name: Build
        run: cmake --build build --target all

      - name: Package
        run: cmake --build build --target package

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: ${{ github.ref_name != 'master' }}
          tag_name: ${{ github.ref_name == 'master' && 'dev' || github.ref_name }}
          prerelease: ${{ github.ref_name == 'master' }}
          files: build/${{ env.OUTNAME }}.zip

  release-windose:
    name: Publish Win${{ matrix.bits }} binaries
    runs-on: windows-latest
    permissions:
      contents: write

    strategy:
      matrix:
        bits: [32, 64]

    env:
      CACHE_BUST: 1
      OUTNAME: Klawiatura-${{ github.ref_name == 'master' && 'dev' || github.ref_name }}-Win${{ matrix.bits }}

    steps:
      - name: Silence `git init` warning
        run: git config --global init.defaultBranch master

      - name: Checkout
        uses: actions/checkout@v7

      - name: Source Discord Social SDK
        shell: bash
        run: |
          cd external/discord
          git init
          git remote add origin https://${{ secrets.EXTERNAL_TOKEN }}@github.com/${{ secrets.EXTERNAL_USER }}/discord.git
          git pull origin master

      - name: Restore source timestamps for crazy CMake caching benefits
        uses: chetan/git-restore-mtime-action@v2

      - name: Install dependencies
        run: py -m pip install jinja2

      - name: Cache build dir
        id: cache-build
        uses: actions/cache@v6
        with:
          path: build
          key: ${{ env.CACHE_BUST }}-Win${{ matrix.bits }}-${{ github.ref_name }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ env.CACHE_BUST }}-Win${{ matrix.bits }}-${{ github.ref_name }}-
            ${{ env.CACHE_BUST }}-Win${{ matrix.bits }}-

      - name: Configure
        shell: bash
        run: |
          cmake -G "Visual Studio 18 2026" -A ${{ matrix.bits == 32 && 'Win32' || 'x64' }} \
            -S . -B build \
            -D CPACK_PACKAGE_FILE_NAME=${{ env.OUTNAME }}

      - name: Build
        run: cmake --build build --target all --config Release

      - name: Package
        run: cmake --build build --target package --config Release

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: ${{ github.ref_name != 'master' }}
          tag_name: ${{ github.ref_name == 'master' && 'dev' || github.ref_name }}
          prerelease: ${{ github.ref_name == 'master' }}
          files: build/${{ env.OUTNAME }}.zip

  release-html5:
    name: Publish the HTML5 build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    env:
      CACHE_BUST: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Restore source timestamps for crazy CMake caching benefits
        uses: chetan/git-restore-mtime-action@v2

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          version: 1.1
          packages: ${{ env.CRAZY_AHH_DEPS }} nodejs

      - name: Source pasture-raised gluten-free emsdk
        uses: emscripten-core/setup-emsdk@main
        with:
          version: latest
          actions-cache-folder: emsdk-cache

      - name: Cache build dir
        id: cache-build
        uses: actions/cache@v6
        with:
          path: build
          key: ${{ env.CACHE_BUST }}-Web-${{ github.ref_name }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ env.CACHE_BUST }}-Web-${{ github.ref_name }}-
            ${{ env.CACHE_BUST }}-Web-

      - name: Configure
        run: emcmake cmake -G Ninja -S . -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target Klawiatura

      - name: Prepare for distibution
        run: cp -vr build/Klawiatura.{js,wasm,data} www

      - name: Publish
        id: publish
        uses: nonk123/sanity-action@master
        with:
          push_to_github_pages: true
